### PR TITLE
adds the dune build system

### LINKED ISSUE #66: Port to Dune build system
[Dune](https://dune.build) is the new de-facto standard in OCaml world, greatly simplifying building, maintenance, vendoring, and developing the code. It would improve a lot of things in piqi.

### PR DESCRIPTION
**Pull request by ivg**
The existing build system based on OCamlMake files is left untouched. We build only essentials with dune, so right now tests, booting, and code generation is not implemented. We can port the rest, but I would suggest to do it in a separate PR.

Note, that we're currently moving BAP to dune and to the dune plugin system and piqi is a road blocker for us, since it doesn't provide the cmxs file that enables dynamic loading. I was thinking about fixing the OCamlMakefile... but decided that porting to dune is a much easier task)  Also, moving piqi to dune will  enable vendoring piqi into duniverse, which is our ultimate goal.

I will soon push a PR to ocaml-piqi and if you will accept both, I can work on make the opam-repository PR, if you want. 

Fixes #66

### CODE REVIEW

**Comment by alavrik** [comment]
@ivg thank you for contributing this. This dune thing look pretty neat and seems to work. I'll be honest I am not up to date with the state of OCaml ecosystem.

I've made one small change to simplify and make this cleaner in terms of naming: https://github.com/alavrik/piqi/pull/68/commits/7632b07e9a071b3a2ce9a1f84f33671b61f04a4c

Hope this is ok? Let me know what you think and I'll have this merged in.

On a related topic, do you need to turn this into an official opam release to use? Or you are happy with the dev version? I am not at all familiar with duniverse.

**Comment by ivg** [comment]
Yes, I was pretty confused with the package naming. Ideally, we should have a one-to-one correspondence between the packages defined in dune and the opam packages that we release via the opam-repository. At least it is how it was designed. 

> On a related topic, do you need to turn this into an official opam release to use?

Yes, eventually I will need this to be released to opam-repository so that people can do `opam install bap` and it will pull the piqi dependency that is built with dune (which includes the properly built cmxs files). But this will just require updating the opam files.

**Comment by alavrik** [comment]
Ok this is merged now. Would you be able to help with opem-repository? Let me know when you want me to cut a new release for it.

**Comment by alavrik** [comment]
@ivg by the way, that's the best CI for open-source ocaml projects? Travis-ci seems to be no longer working, at least by default.

**Comment by ivg** [comment]
> Ok this is merged now. Would you be able to help with opem-repository? Let me know when you want me to cut a new release for it.

Sure, I will prepare the PR. I will cc-you when I it will be ready. I will need the release eventually, but let me check first that everything works fine with my own opam-repository.



> @ivg by the way, that's the best CI for open-source ocaml projects these days? Travis-ci seems to be no longer working, at least by default.

Github action is what we're using in BAP and what is recommended. If you're interested I can make a PR that adds CI, at least building for starters. Don't recall if you need to enable something in the repository settings, but we will figure it out)

**Pull request merged**
